//! Task contract: tool_call in, tool_result out.
//!
//! The contract is intentionally transport-agnostic: the same frames ride the
//! outbound WS connection, the degraded chunked-delivery channel, or any
//! future carrier. Nothing here knows about serialization beyond serde.
//!
//! The Probe is skill-blind: it executes the operation handed to it and
//! nothing else. Skills live in the Krystallizer graph and are resolved by
//! Gravity / the LLM; what reaches the Probe is only an operation and its
//! arguments.

use serde::{Deserialize, Serialize};

/// One operation arriving at the Probe.
///
/// The Probe ships no built-in operations and keeps no registry. `session`
/// is the caller's opaque residency identity and `entry` names the point the
/// delivered code exposes; `code` always carries its executable part.
/// `language` names the carrier to run it in — the node must carry it
/// (registration advertises carried languages) or the call is an error value.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    /// Correlates the eventual ToolResult back to the caller (Gravity's
    /// pending_calls deadline scan reuses this id).
    pub call_id: String,
    /// Opaque residency identity, minted by the caller: the Probe keys its
    /// resident session by this value, so calls sharing a `session` share
    /// runtime state (VM / module globals) and calls with different values
    /// never do. The Probe derives nothing from it beyond identity — an
    /// upstream actor's `type/key` is the natural value. It cannot be the
    /// per-call id: residency needs an identity that is stable across calls,
    /// or every call would start a cold runtime.
    pub session: String,
    /// Entry point inside the delivered code — the function/event name the
    /// code binds, whichever convention it uses. This is NOT a lookup key:
    /// the Probe resolves nothing against it (no registration, no
    /// validation). A name the code does not bind falls back to the
    /// conventional `execute` entry when the code defines one, and is an
    /// error value otherwise.
    pub entry: String,
    /// Carrier to execute in ("nushell", "python", "steel", "wasmtime").
    pub language: String,
    /// Arguments generated by the LLM — instruction semantics (paths,
    /// options, fragments). AI-generated args are naturally bounded; the
    /// control plane's loose message cap is the only guard, per PLAN
    /// (data-path discipline).
    pub args: serde_json::Value,
    /// The operation's code. Always present: there is no native-operation
    /// path — the Probe provides runtimes, not logic.
    pub code: CodePayload,
}

/// The Probe's answer, message-sized by discipline.
///
/// Large artifacts never enter the control plane: the operation handles them
/// on the Probe side (local fs, user-configured transfer tooling, transport
/// skills). `Result` stays a summary.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolResult {
    pub call_id: String,
    pub outcome: Result<serde_json::Value, String>,
}

/// Executable code delivered with an operation.
///
/// Small scripts (py/steel, KB-scale) ride inline in the frame. Larger
/// artifacts (Wasm, MB-scale) go by versioned URL: content-hash version, so
/// the URL is its own invalidation policy (CDN-friendly caching, not a
/// Probe-side code cache). When only the WS channel is reachable, the
/// control plane assembles `link` as chunked delivery over the same frames;
/// the Probe consumes whichever form is declared.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum CodePayload {
    /// Bytes in the frame.
    Inline { bytes: Vec<u8> },
    /// URL + content-hash version + expected hash.
    Link {
        url: String,
        version: String,
        expected_sha256: String,
    },
}


/// Transport envelope over the outbound connection (Phase 3). The control
/// plane sends exactly one frame per WS message; the probe replies likewise.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Frame {
    /// Probe to control plane, once per connection.
    Register {
        node_alias: String,
        credential: String,
        carriers: Vec<String>,
    },
    /// Control plane to probe: a `Register` was accepted.
    Registered,
    /// Control plane to probe: one operation.
    Call(ToolCall),
    /// Probe to control plane: the operation's answer.
    Result(ToolResult),
    /// Bidirectional: a host-function round trip (ctx bridge over the
    /// wire). Probe -> control plane = Call, control plane -> probe =
    /// Result; the `host_call_id` correlates. The control plane resolves
    /// the call against the ACTOR INSTANCE that the enclosing ToolCall was
    /// routed to (the gateway tracks call_id -> instance; ctx state is
    /// scoped to that instance's own fields).
    Host(HostFrame),
}

/// One host-function round trip (ctx over the wire).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum HostFrame {
    Call(HostCall),
    Result(HostResult),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HostCall {
    pub host_call_id: String,
    /// The enclosing ToolCall's id — the control plane resolves the ctx
    /// scope (actor instance) from it.
    pub call_id: String,
    pub op: HostOp,
}

/// The ctx surface scripts can reach, carried op-by-op. `state_*` touches
/// the instance's own fields (cross-instance reach is not expressible);
/// `invoke` rides the control plane's unified call model.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "op", rename_all = "snake_case")]
pub enum HostOp {
    Invoke {
        target_type: String,
        target_key: String,
        handler: String,
        args: serde_json::Value,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HostResult {
    pub host_call_id: String,
    pub outcome: Result<serde_json::Value, String>,
}
