//! Task contract: tool_call in, tool_result out.
//!
//! The contract is intentionally transport-agnostic: the same frames ride the
//! outbound WS connection, the degraded chunked-delivery channel, or any
//! future carrier. Nothing here knows about serialization beyond serde.
//!
//! The Probe is skill-blind: it executes the operation handed to it and
//! nothing else. Skills live in the Krystallizer graph and are resolved by
//! Gravity / the LLM; what reaches the Probe is only an operation and its
//! arguments.

use serde::{Deserialize, Serialize};

/// One operation arriving at the Probe.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    /// Correlates the eventual ToolResult back to the caller (Gravity's
    /// pending_calls deadline scan reuses this id).
    pub call_id: String,
    /// Target capability on this node, e.g. `probe:home-pc:read_file`.
    pub tool: String,
    /// Arguments generated by the LLM — instruction semantics (paths,
    /// options, fragments). AI-generated args are naturally bounded; the
    /// control plane's loose message cap is the only guard, per PLAN
    /// (data-path discipline).
    pub args: serde_json::Value,
    /// Code the operation runs, when it is not a host capability the Probe
    /// provides natively. The Probe does not interpret this as a "skill" —
    /// it is just the operation's executable part.
    pub code: Option<CodePayload>,
}

/// The Probe's answer, message-sized by discipline.
///
/// Large artifacts never enter the control plane: the operation handles them
/// on the Probe side (local fs, user-configured transfer tooling, transport
/// skills). `Result` stays a summary.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolResult {
    pub call_id: String,
    pub outcome: Result<serde_json::Value, String>,
}

/// Executable code delivered with an operation.
///
/// Small scripts (py/steel, KB-scale) ride inline in the frame. Larger
/// artifacts (Wasm, MB-scale) go by versioned URL: content-hash version, so
/// the URL is its own invalidation policy (CDN-friendly caching, not a
/// Probe-side code cache). When only the WS channel is reachable, the
/// control plane assembles `link` as chunked delivery over the same frames;
/// the Probe consumes whichever form is declared.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum CodePayload {
    /// Bytes in the frame.
    Inline { bytes: Vec<u8> },
    /// URL + content-hash version + expected hash.
    Link {
        url: String,
        version: String,
        expected_sha256: String,
    },
}
