//! Language carriers: the three settled engines, feature-gated.
//!
//! Every carrier exposes the same contract: source in, JSON value out. The
//! runtime does not interpret what the script means — it received an
//! operation from the control plane and runs its executable part.

use serde_json::Value;

/// What a carrier needs to execute one operation.
/// Host-provided functions callable from inside an operation. Each takes
/// one JSON argument and returns a JSON result (or an error). The caller
/// (actuator or embedded host) supplies state access, invoke, emit — the
/// carrier only marshals values across the VM boundary.
pub type HostFn = std::sync::Arc<dyn Fn(Value) -> anyhow::Result<Value> + Send + Sync>;

/// The host-injected byte-level engine face (ADR-0037 4.16a). FOUR
/// closures in okm's `VirtualStorage` shapes — bytes in, bytes out.
/// The slot carries NO okm/aura types on purpose: the contract is
/// rev-independent, which is what lets the host (aura) hold a
/// different okm build than the binding (okm-python) without the
/// cross-repo type identity question ever arising. Semantics mirror
/// okm's engine rules: ordered keys, `None` end = unbounded,
/// scan returns FULL keys (the caller's coordinate space).
pub type PutFn = std::sync::Arc<dyn Fn(Vec<u8>, Vec<u8>) + Send + Sync>;
pub type GetFn = std::sync::Arc<dyn Fn(&[u8]) -> Option<Vec<u8>> + Send + Sync>;
pub type DelFn = std::sync::Arc<dyn Fn(&[u8]) + Send + Sync>;
pub type ScanRangeFn = std::sync::Arc<dyn Fn(&[u8], Option<&[u8]>) -> Vec<Vec<u8>> + Send + Sync>;

pub struct StorageEngineFns {
    pub put: PutFn,
    pub get: GetFn,
    pub del: DelFn,
    pub scan_range: ScanRangeFn,
}

/// One declared collection of the injection slot: the RAW entry shape
/// `Collection::with_store` consumes —
/// `{ "schema": <CollectionSchema serde>, "indexes": [...], "reduces": [...] }`
/// (ns NOT in the entry — the DSL's rule; the slot binds it).
pub struct StorageCollection {
    pub name: String,
    pub entry: serde_json::Value,
}

/// The python carrier's storage injection slot (ADR-0037 §1): the
/// host's live engine behind the byte face + the type's declared
/// collections. The carrier's load step builds one `Collection` per
/// entry over this engine and registers it into the module namespace
/// under the collection name — the script's binding face, zero
/// translation. Other carriers ignore the slot (steel envelope ops
/// ride `ctx_store_emit`; wasmtime rides its own raw `emit` HostFn).
pub struct StorageSlot {
    pub ns: u16,
    pub collections: Vec<StorageCollection>,
    pub engine: std::sync::Arc<StorageEngineFns>,
}

/// Named host functions for one execution. `None` = pure operation
/// (no host contact), the current default.
#[derive(Clone, Default)]
pub struct HostBridge {
    pub functions: std::collections::BTreeMap<String, HostFn>,
    /// Storage injection (python carrier only; `None` = no collections).
    pub storage: Option<std::sync::Arc<StorageSlot>>,
}

pub struct ExecRequest<'a> {
    /// Operation source code (from `ToolCall.code` inline bytes, or fetched
    /// by the caller from a `link` payload before dispatch).
    pub source: &'a str,
    /// Entry point the operation declares (function name); `None` = run the
    /// script top-level and use its result.
    pub entry: Option<&'a str>,
    /// JSON arguments generated by the LLM.
    pub args: &'a Value,
    /// Host functions exposed to the operation (state/invoke/...). `None`
    /// for pure operations.
    pub host: Option<&'a HostBridge>,
}

pub type ExecResult = anyhow::Result<Value>;

#[cfg(feature = "steel")]
pub mod steel;
#[cfg(feature = "python")]
pub mod python;
#[cfg(feature = "wasmtime")]
pub mod wasmtime;
pub mod exec;
pub mod session;

/// Dispatch by declared language. Unknown language = error value, never a
/// panic: the control plane declared it, the Probe only validates.
pub fn execute(language: &str, _req: ExecRequest) -> anyhow::Result<Value> {
    match language {
        #[cfg(feature = "steel")]
        "steel" => anyhow::bail!("steel is resident-only: use carrier::session"),
        #[cfg(feature = "python")]
        "python" => anyhow::bail!("python is resident-only: use carrier::session"),
        #[cfg(feature = "wasmtime")]
        "wasmtime" => anyhow::bail!("wasmtime is resident-only: use carrier::session"),
        other => anyhow::bail!("language not carried by this probe build: {other}"),
    }
}

/// Upload-time introspection, dispatched per language. Every carrier
/// assembles/merges `interface_schema` behind this one call — the host
/// never knows how each language collects its declarations.
pub fn introspect(language: &str, source: &str) -> anyhow::Result<Value> {
    introspect_encoded(language, source, probe_protocol::ChannelEncoding::Json)
}

/// The declared-encoding form (ADR-0037 §2): the process carriers spawn
/// their throwaway session in the DECLARED codec — a CBOR-declared bgi
/// booth's `interface_schema` frame round trip must ride CBOR too, or
/// the child would not parse the request.
pub fn introspect_encoded(
    language: &str,
    source: &str,
    encoding: probe_protocol::ChannelEncoding,
) -> anyhow::Result<Value> {
    match language {
        #[cfg(feature = "steel")]
        "steel" => steel::introspect(source),
        #[cfg(feature = "python")]
        "python" => python::introspect(source),
        #[cfg(feature = "wasmtime")]
        "wasmtime" => {
            // Explicit `interface_schema` export wins; otherwise the
            // receives half derives from the export list. One throwaway
            // session, same shape as every carrier's introspection.
            // The bridge carries a STUB `emit` (the steel register_ctx_stubs
            // precedent): a wasm storage module imports aura_host.emit, but
            // at introspection time no store plan exists — the import must
            // be satisfied for instantiation without being callable (the
            // schema export is a pure declaration, never an emit).
            let mut stub = HostBridge::default();
            stub.functions.insert(
                "emit".into(),
                std::sync::Arc::new(|_arg: Value| {
                    anyhow::bail!("emit is not callable during introspection")
                }),
            );
            let sessions = session::Sessions::new();
            sessions.with_session(
                "__introspect",
                language,
                source,
                Some(&stub),
                &crate::sandbox::SandboxPolicy::None,
                |s: &mut dyn crate::carrier::session::ResidentSession| match s
                    .as_any()
                    .downcast_mut::<wasmtime::WasmSession>()
                {
                    Some(w) => w.introspect(),
                    None => s.call(crate::carrier::wasmtime::SCHEMA, &Value::Null),
                },
            )
        }
        // Languages without collectors: the script hand-writes the whole
        // `interface_schema` — run it in a THROWAWAY resident session
        // (load, call the schema function, drop). Same contract, no
        // one-shot execution path.
        _ => {
            let sessions = session::Sessions::new();
            sessions.with_session_encoded(
                "__introspect",
                language,
                source,
                None,
                &crate::sandbox::SandboxPolicy::None,
                encoding,
                |s: &mut dyn crate::carrier::session::ResidentSession| {
                    s.call("interface_schema", &Value::Null)
                },
            )
        }
    }
}

