//! Language carriers: the three settled engines, feature-gated.
//!
//! Every carrier exposes the same contract: source in, JSON value out. The
//! runtime does not interpret what the script means — it received an
//! operation from the control plane and runs its executable part.

use serde_json::Value;

/// What a carrier needs to execute one operation.
pub struct ExecRequest<'a> {
    /// Operation source code (from `ToolCall.code` inline bytes, or fetched
    /// by the caller from a `link` payload before dispatch).
    pub source: &'a str,
    /// Entry point the operation declares (function name); `None` = run the
    /// script top-level and use its result.
    pub entry: Option<&'a str>,
    /// JSON arguments generated by the LLM.
    pub args: &'a Value,
}

pub type ExecResult = anyhow::Result<Value>;

#[cfg(feature = "steel")]
pub mod steel;
#[cfg(feature = "python")]
pub mod python;
#[cfg(feature = "wasmtime")]
pub mod wasmtime;
#[cfg(feature = "nushell")]
pub mod nushell;

/// Dispatch by declared language. Unknown language = error value, never a
/// panic: the control plane declared it, the Probe only validates.
pub fn execute(language: &str, req: ExecRequest) -> anyhow::Result<Value> {
    match language {
        #[cfg(feature = "steel")]
        "steel" => steel::execute(req),
        #[cfg(feature = "python")]
        "python" => python::execute(req),
        #[cfg(feature = "wasmtime")]
        "wasmtime" => wasmtime::execute(req),
        #[cfg(feature = "nushell")]
        "nushell" => nushell::execute(req),
        other => anyhow::bail!("language not carried by this probe build: {other}"),
    }
}

