//! Language carriers: the three settled engines, feature-gated.
//!
//! Every carrier exposes the same contract: source in, JSON value out. The
//! runtime does not interpret what the script means — it received an
//! operation from the control plane and runs its executable part.

use serde_json::Value;

/// What a carrier needs to execute one operation.
/// Host-provided functions callable from inside an operation. Each takes
/// one JSON argument and returns a JSON result (or an error). The caller
/// (actuator or embedded host) supplies state access, invoke, emit — the
/// carrier only marshals values across the VM boundary.
pub type HostFn = std::sync::Arc<dyn Fn(Value) -> anyhow::Result<Value> + Send + Sync>;

/// Named host functions for one execution. `None` = pure operation
/// (no host contact), the current default.
#[derive(Clone, Default)]
pub struct HostBridge {
    pub functions: std::collections::BTreeMap<String, HostFn>,
}

pub struct ExecRequest<'a> {
    /// Operation source code (from `ToolCall.code` inline bytes, or fetched
    /// by the caller from a `link` payload before dispatch).
    pub source: &'a str,
    /// Entry point the operation declares (function name); `None` = run the
    /// script top-level and use its result.
    pub entry: Option<&'a str>,
    /// JSON arguments generated by the LLM.
    pub args: &'a Value,
    /// Host functions exposed to the operation (state/invoke/...). `None`
    /// for pure operations.
    pub host: Option<&'a HostBridge>,
}

pub type ExecResult = anyhow::Result<Value>;

#[cfg(feature = "steel")]
pub mod steel;
#[cfg(feature = "python")]
pub mod python;
#[cfg(feature = "wasmtime")]
pub mod wasmtime;
#[cfg(feature = "nushell")]
pub mod nushell;
#[cfg(feature = "nushell")]
pub mod nushell_session;
pub mod session;

/// Dispatch by declared language. Unknown language = error value, never a
/// panic: the control plane declared it, the Probe only validates.
pub fn execute(language: &str, req: ExecRequest) -> anyhow::Result<Value> {
    match language {
        #[cfg(feature = "steel")]
        "steel" => anyhow::bail!("steel is resident-only: use carrier::session"),
        #[cfg(feature = "python")]
        "python" => anyhow::bail!("python is resident-only: use carrier::session"),
        #[cfg(feature = "wasmtime")]
        "wasmtime" => wasmtime::execute(req),
        #[cfg(feature = "nushell")]
        "nushell" => anyhow::bail!("nushell is resident-only: use carrier::session (no one-shot execution)"),
        other => anyhow::bail!("language not carried by this probe build: {other}"),
    }
}

/// Upload-time introspection, dispatched per language. Every carrier
/// assembles/merges `interface_schema` behind this one call — the host
/// never knows how each language collects its declarations.
pub fn introspect(language: &str, source: &str) -> anyhow::Result<Value> {
    match language {
        #[cfg(feature = "steel")]
        "steel" => steel::introspect(source),
        #[cfg(feature = "python")]
        "python" => python::introspect(source),
        // Languages without collectors: the script hand-writes the whole
        // `interface_schema` — run it in a THROWAWAY resident session
        // (load, call the schema function, drop). Same contract, no
        // one-shot execution path.
        _ => {
            let sessions = session::Sessions::new();
            sessions.with_session("__introspect", language, source, None, |s| {
                s.call("interface_schema", &Value::Null)
            })
        }
    }
}

