[package]
name = "actor-guest"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
okm-core = { git = "https://github.com/orbsh/okm", default-features = false, features = ["schema-serde"] }
okm-wire = { git = "https://github.com/orbsh/okm" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ciborium = "0.2"

[[example]]
name = "counter_actor"
crate-type = ["cdylib"]

[lints.rust]
unexpected_cfgs = { level = "allow" }
